### ISSUE TITLE
Implementações - Adição de Funções

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#104]
* Em `TelaCadastroAmigos`, adicionar a função de `visualizar `empréstimos ativos de um amigo quando a aba dele estiver selecionada e também de `criar novo empréstimo` a partir da tela de `Dados Cadastrais`.

* Adicionar também uma função de, quando a `TelaCadastroAmigos` estiver sendo utilizada para `criação` e não `visualização` dos dados cadastrais, os botões de `Mais` e o botão do `Olho`, sejam desligados, ou seja, que o usuário não possa clicar neles.

Dúvidas podem ser enviadas nessa issue.

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/e20d308a-1b2a-40b4-a874-a758dfa0df0d)

**Comment by lucasGFlores** [comment]
#136 feito >:)
perdi 3 neurônios
