### ISSUE TITLE
Implementações - Tela Cadastro Fabricantes

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#107]
* Remover botão de cadastro sem verificação
* Corrigir botão de cancelar que não está funcionando
* Permitir que o usuário cadastro o fabricante sem consultar o CNPJ, desde que os campos de CNPJ e Nome da Empresa estejam preenchidos.

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/9b3bafa3-9e18-401b-8f90-e0f571883cc2)

**Comment by lucasGFlores** [comment]
@yLuffe  os botões estão invertidos ou estão certo??
Tipo o disquete com mais "+" é o de cancelar e o com o menos "-" é para finalizar.
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/82884204/369f0aeb-7ca3-4976-bd69-8818787bac38)

**Comment by yLuffe** [comment]
O nome dos botões por algum motivo está trocado, porém se você testar, eles vão estar com as funções corretas. Em alguma parte do processo de construção da parte visual, posso ter trocado suas funções, ou até mesmo na hora de renomear a variável, se quiser, pode alterar o nome e também arrumar as funções, porém, se estiver funcionando, está de boa :)

**Comment by lucasGFlores** [comment]
sim eu percebi que a programação estava certinha, só fiquei encucado se eu tava seguindo a issue corretamente

**Comment by lucasGFlores** [comment]
#110
