### ISSUE TITLE
Implementação - Botão Deletar

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#116]
- Adicionar função para o botão de `Deletar` em todas as quatro tabelas que temos disponíveis na tela inicial

- Esses botões são configurados a partir dos seguintes arquivos: Pasta: `Views.Screens` -> `Screen+NomeDaTela`

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/ec4faca2-e67c-4386-a2d4-c3bf26ca50e5)

**Comment by lucasGFlores** [comment]
#133 
feito
