### ISSUE TITLE
Implementação - Mudança Texto

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#117]
- Remover a palavra `Selecionado` após o fabricante estar selecionado.

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/9d25e14a-20da-4184-af98-d97851cae67e)

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/d2b1051c-bbf7-41a4-9d9f-fc662553235e)

**Comment by lucasGFlores** [comment]
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/82884204/1bc6c1bc-d2f7-4037-bd22-20aafea1b6dd)
ja foi resolvido
