### ISSUE TITLE
Exception - Tela Cadastro Ferramenta

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#118]
- Exception não sendo tratada quando é feita uma tentativa de cadastro sem selecionar um fornecedor.

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/172df5c0-b2e9-4088-800f-f3fd7946f4c4)

**Comment by lucasGFlores** [comment]
#127 feito
