### ISSUE TITLE
Bug - Tela Selecionar Fabricante

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#121]
- Pequeno erro devido a remoção de uma CheckBox.

- Field de filtro foi substituído.
- Adicionar função a lupa de pesquisa.
- Nessa mesma tela, a tabela não está sendo carregada

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/631f6771-bf4e-4a34-a1a1-b7e9265d1b83)

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/3ce14cfe-1075-4ab8-bc70-ecdb7afb2a10)

**Comment by lucasGFlores** [comment]
Qual é o nome da tela???

**Comment by lucasGFlores** [comment]
precisa mais não, já encontrei

**Comment by lucasGFlores** [comment]
#125 foi feito, parsa
