### ISSUE TITLE
Bug - Amigo com Pendências

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#138]
- Utilizado anteriormente, porém não mais presente na versão atual do software, temos um pequeno problema de Back End a ser resolvido. Quando aquele seu amigo caloteiro te deve algo, você não pode simplesmente deleta-lo e esquecer a dívida, a não ser que ele já esteja com tudo quitado. Bem, algo semelhante está acontecendo, quando um caloteiro está com um pendências no sistema, o seu cadastro não é excluído, porém, não é exibida nenhum mensagem do tipo `O cadastro de {nome_amigo} não pode ser excluído por possuí pendências no sistema!`, sendo assim, você pode até tentar "excluir" quem deve algo, porém, o mesmo não será, e nenhum mensagem de erro retorna ao usuário.

Ps.: Todo um enredo por trás da Issue. Só pra irritar o Lucas

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/837110a7-2c59-4407-aede-9233a5128ee9)

**Comment by lucasGFlores** [comment]
kkkkk
fi da mãe

**Comment by lucasGFlores** [comment]
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/82884204/61cb0d83-aa5f-4c8c-97d7-568fb5d19736)
Enfim, já que parece que está funcionando eu vou fechar a issue
