### ISSUE TITLE
Correção - Tabela Selecionar Ferramenta em Cadastro Empréstimo

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#140]
- Mesmo esquema do #121 

@lucasGFlores se quiser, pode meter bala nessa, é a mesma coisa daquela outra que destaquei ali em cima.

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/aab471a1-fa3a-4f13-84d2-d3bb23256580)

**Comment by yLuffe** [comment]
O caminho dessa pelo Software é `Empréstimos em Aberto` -> `Cadastrar Novo Empréstimo` -> `Adicionar Ferramenta`

O local no projeto é `ViewsTool -> TelaSelecionarFerramenta.java`

**Comment by lucasGFlores** [comment]
Beleza, já vou ir fazer

**Comment by lucasGFlores** [comment]
#144 
Man, fiquei meia hora na tela errada, pensei que tava ficando louco. É foda a vida
