### ISSUE TITLE
Exception - Deletar Cadastros

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#142]
- `java.lang.ArrayIndexOutOfBoundsException` quando ocorre tentativa de deletar algum elemento da tabela que não está selecionado.

- Quando você não seleciona nenhum elemento da tabela, sejam eles, amigos, empréstimos, ferramentas ou fabricantes e tenta excluir, sem ter selecionado, o erro é exibido no log.

- Tratar exception porém não exibir mensagem na tela.

**Comment by lucasGFlores** [comment]
#170 
dei uma melhorada nos erros mostra mais
