### ISSUE TITLE
Lucas não me mata por favor

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#145]
- @lucasGFlores mesma coisa da #140 

- Agora é em `TelaTabelaAmigos` no packege `ViewsAmigos`.
- Para testar, é só ir na tela da imagem 2. 

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/a93a4865-708c-4d7e-afe0-f0b59b9e676b)

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/15ce6e13-ae9a-4c93-9ba8-e16709e27453)

**Comment by yLuffe** [comment]
- Tem que desbloquear o campo da busca por nome e ver se o botão de search tá funfando

![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/96a16b20-85ae-44e7-b190-6f0b4a5117e5)

**Comment by lucasGFlores** [comment]
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/82884204/603c3339-caac-4f61-a182-91755a3da180)
Corre

**Comment by lucasGFlores** [comment]
#157 feito demorei mais pq fiquei corrigindo coisas paralelas
