### ISSUE TITLE
Bug - Google

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#166]
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/62aa356c-f2ac-43d8-94c7-1d7182809123)

**Comment by xrkmed** [comment]
Dá mais detalhes sobre quando ocorre isso

**Comment by yLuffe** [comment]
- Agora apareceu isso no log do sistema @xrkmed 
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/dcf5f84f-0370-4c58-9b08-9d503aa39594)

**Comment by xrkmed** [comment]
Mas isso ocorre quando voce ta fazendo um cadastro? alterando um cadastro?
inserindo um cep?

**Comment by yLuffe** [comment]
Abrindo a tela de adição, exemplo, seleciona a Maria e clica em editar, ai aparece o erro
