### ISSUE TITLE
Bug - Tela Atribuir Fabricante

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#205]
* Erro ao abrir TelaAtrbuirFabricante, por meio do botão de edição em TelaFabricantes na TelaInicial
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/132414913/1eddd7b4-e7dd-475b-ab74-45de5fb3ac9d)

**Comment by lucasGFlores** [comment]
já que essa tela não existe mais eu vou tirar a issue
