### ISSUE TITLE
Adição Valor Fictícios DB

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#30]
@xrkmed Limpar a DataBase atual, resetar o Auto Increment e criar valores fictícios para as tabelas: Ferramentas, Amigos e Fabricantes. (Utilizar ChatGPT para conclusão mais rápida).

**Comment by xrkmed** [comment]
Valores ficticios adicionados
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/114001978/2dfcfc8d-0409-4566-a1f9-cd6e3ef5a0f4)
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/114001978/bbda3942-848f-43b6-b5b8-06a8b5518881)
![image](https://github.com/xrkmed/Unisul_EmprestimoDeFerramentasApp/assets/114001978/dbea3906-2a44-4357-86e7-a0383d89c0d3)
