### ISSUE TITLE
Erro no Código #1

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#32]
* Erro no código em src.ViewsEmprestimo.TelaCadastroEmprestimo na linha 61 
 * `jLabel1.setText("Alterar emprestimo");` -> Corrigir texto para "Alterar Empréstimo"

**Comment by CarlulsNex** [comment]
Corrigi esse naquele mesmo dos tooltiptext, acredito que revisei a maioria dos textos que tinha ate aquele momento.
