### ISSUE TITLE
Erro no Código #2

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#33]
Erro no código em src.ViewsTool.TelaSelecionarFabricante, nas linhas 408 e 409 com o componente " TelaEditarFerramenta "

`try{
                if(parent instanceof TelaCadastro){
                    ((TelaCadastro)parent).updateFabricante(selectedManufacturer);
                }else if(parent instanceof TelaEditarFerramenta){
                    ((TelaEditarFerramenta)parent).updateFabricante(selectedManufacturer);
                }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Erro ao atualizar fabricante: " + e.getMessage());
                }`

**Comment by CarlulsNex** [comment]
Já corrigi isso na minha branch
