### ISSUE TITLE
Adicionar funçao nos botoes em tela de amigos cadastrados

### ISSUE THREAD

**Issue by xrkmed** [xrkmed/Unisul_EmprestimoDeFerramentasApp#4]
Atualmente, apenas o botao "Remover Cadastro" e "Alterar dados cadastrais" estao funcionais, precisa adicionar funçao aos botoes "Visualizar todos os emprestimos", "Relatorio de ferramentas" e aos filtros "Apenas amigos que estejam em um emprestimo", "Apenas amigos que devem devolver alguma ferramenta" e "Apenas amigos sem emprestimos em aberto"

**Comment by PauloEMGAlexandre** [comment]
O botão "Relatorio de ferramentas" retorna o mesmo relatório acessível pela tela principal, ou um relatório contendo só as ferramentas associadas ao amigo selecionado na tela de amigos cadastrados?
