### ISSUE TITLE
Avaliar necessidade do botao MenuItem Ranking de Amigos

### ISSUE THREAD

**Issue by xrkmed** [xrkmed/Unisul_EmprestimoDeFerramentasApp#6]
Avaliar necessidade de adicionar funcionalidade ou implementar diretamente a funcionalidade no relatorio de amigos...

**Comment by lucasGFlores** [comment]
bem... eu já acabei fazendo. Mas realmente não parece ter uma necessidade muito grande, apenas uma funcionalidade extra para a gente contemplar minimamente.
