### ISSUE TITLE
Implementação - Exportar em PDF

### ISSUE THREAD

**Issue by yLuffe** [xrkmed/Unisul_EmprestimoDeFerramentasApp#84]
* Todos as telas de exportação de relatório devem ser excluídas, porém, antes deve ser implementada a mesma função no botão de icone `PDF` em `TelaInicial`. O sistema deve ser capaz de detectar em qual aba o usuário está, Amigos, Empréstimos, Ferramentas ou Fabricantes, e gerar um relatório de acordo com a lista.

**Comment by xrkmed** [comment]
Sistema adicionado no Pull Request #89
