### ISSUE TITLE
Implementações #3

### ISSUE THREAD

**Issue by xrkmed** [xrkmed/Unisul_EmprestimoDeFerramentasApp#9]
* Adicionar Funcionalidade ao `MenuItem Relatório` de `Fabricantes`

**Comment by lucasGFlores** [comment]
#49

**Comment by xrkmed** [comment]
> Fiz rapidin #49

Esse ai e o relatorio de amigos, tem o de fabricantes tb @lucasGFlores

**Comment by lucasGFlores** [comment]
Perdão,como assim
